# Generated by Django 5.1.4 on 2024-12-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_group'),
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='traits',
        ),
        migrations.AddField(
            model_name='pet',
            name='traits',
            field=models.ManyToManyField(related_name='traits', to='traits.trait'),
        ),
    ]
