# Generated by Django 5.1.4 on 2024-12-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0002_trait_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
